package com.neuedu.pojo;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_admin.id
     *
     * @mbggenerated Wed Aug 07 15:08:53 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_admin.username
     *
     * @mbggenerated Wed Aug 07 15:08:53 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_admin.password
     *
     * @mbggenerated Wed Aug 07 15:08:53 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_admin
     *
     * @mbggenerated Wed Aug 07 15:08:53 CST 2019
     */
    public Admin(Integer id, String username, String password) {
        this.id = id;
        this.username = username;
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_admin
     *
     * @mbggenerated Wed Aug 07 15:08:53 CST 2019
     */
    public Admin() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_admin.id
     *
     * @return the value of neuedu_admin.id
     *
     * @mbggenerated Wed Aug 07 15:08:53 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neuedu_admin.id
     *
     * @param id the value for neuedu_admin.id
     *
     * @mbggenerated Wed Aug 07 15:08:53 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_admin.username
     *
     * @return the value of neuedu_admin.username
     *
     * @mbggenerated Wed Aug 07 15:08:53 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neuedu_admin.username
     *
     * @param username the value for neuedu_admin.username
     *
     * @mbggenerated Wed Aug 07 15:08:53 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_admin.password
     *
     * @return the value of neuedu_admin.password
     *
     * @mbggenerated Wed Aug 07 15:08:53 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neuedu_admin.password
     *
     * @param password the value for neuedu_admin.password
     *
     * @mbggenerated Wed Aug 07 15:08:53 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}